### PR TITLE
Kafka removal

### PR DESCRIPTION
**Pull request by ivukotic**
very simple

### CODE REVIEW

**Review by BenGalewsky — APPROVED** [review]
Indeed, quite simple, and overdue

**Comment by oshadura** [comment]
On coffea-casa,I redeployed servicex and now I see a new strange error in transformer: 
```
[root@cmsaf secrets]# kubectl logs -f transformer-ae45b85d-2868-4de7-abee-5bde9d194a3d-6f6475fdbdfkgl -n cmsaf-prod
INFO cmsaf-servicex Uproot-Transformer  none Got proxy.
  File "/servicex/transformer.py", line 317
    if args.result_destination == 'kafka':
     ^
IndentationError: expected an indented block
```
Could it be something related to these changes?

**Comment by oshadura** [comment]
I think there is just something wrong with a code here: https://github.com/ssl-hep/ServiceX_Uproot_Transformer/blob/develop/transformer.py#L315-L317

**Comment by ivukotic** [comment]
I will check and fix it in a min

**Comment by ivukotic** [comment]
this was error in ServiceX_Uproot_Transformer introduced when adding logging. It has been fixed now.

**Pull request merged**
