### PR TITLE
Remove hard-coded images from templates

### PR DESCRIPTION
**Pull request by holzman**
This is reopening https://github.com/ssl-hep/ServiceX/pull/382 on a feature branch.

### CODE REVIEW

**Comment by sthapa** [comment]
This looks good but let me get this tested today

**Comment by sthapa** [comment]
After some thought, can you change the chart to use a if then so that if the image isn't specified, it'll automatically use the docker images but will use the user specified image otherwise?  I think that'll minimize the disruption and let us set a default in case we want to switch to use harbor or some other source.

**Comment by holzman** [comment]
That's why I also changed values.yaml - to provide those defaults (I thought that was best practice).

Do you really want the default values hard-coded into the template?

**Comment by BenGalewsky** [comment]
This is so odd, I could have sworn I merged this months ago. Still...

**Review by BenGalewsky — CHANGES_REQUESTED** [review]
Please update `docs/deployment/reference.md` to show these new values

**Comment by holzman** [comment]
Sure.  Do you want the rest of the commit as-is, or did you want the default in the templates as @sthapa suggested?

**Comment by BenGalewsky** [comment]
Yes - the rest of the commit is perfect. That indeed is what defaults in `values.yaml` is for!

**Comment by sthapa** [comment]
I missed the values.yaml changes but with that, it should be fine.  No need to add conditional logic for this

**Comment by holzman** [comment]
Done.

**Comment by holzman** [comment]
Any issues with merging this? It's been sitting for 3 weeks.

**Review by BenGalewsky — APPROVED** [review]

**Pull request merged**
