### PR TITLE
Update x509 deployment to mount secrets generated by servicex cli

### PR DESCRIPTION
**Pull request by BenGalewsky**
# Problem
The current way of providing grid certs and passphrase to the x509 proxy requires putting them into the helm chart's `values.yaml` - this works, but is not very secure.
Partial solution to #80 

Also, when you delete the helm chart the x509 proxy hangs around.

# Approach
The new servicex-cli has a command for putting the certs and passphrase into a secret. In this
PR we change the x509 deployment to mount this secret instead of the old grid certs ConfigMap and passphrase secret.

Also, to insure the x509 proxy secret is deleted when the helm chart is deleted, we add the creation of an empty x509-secret in the helm chart so it will be cleared upon delete. The X509 secret service will add files to it.

Finally, updated the README to reflect this new configuration process

### CODE REVIEW

**Comment by BenGalewsky** [comment]
@cnweaver - the secret with the cert and passphrase are now created with the cli script [here](https://github.com/ssl-hep/servicex_cli/blob/master/src/servicex/servicex.py)

**Comment by cnweaver** [comment]
I assume you mean https://github.com/ssl-hep/servicex_cli/blob/develop/src/servicex/servicex.py , and, yes, I looked at that for reference. It sounds like that means templates/x509-proxy-secret.yaml is indeed unnecessary?

**Comment by BenGalewsky** [comment]
Ah, I get it - `x509-proxy-secret.yaml` is in the helm chart so that a skeletal secret is deployed with the chart. That means when you delete the chart, the proxy that is created by the x509-secret service also gets deleted.
I added a comment to the yaml file to clarify

**Comment by cnweaver** [comment]
Okay, that's a clever trick. However, it still looks like the name of the secret doesn't match, `{{ .Release.Name }}-x509-proxy` vs. `grid-certs-secret`.

**Pull request merged**
